export const FETCH_BIO_SUCCESS="FETCH_BIO_SUCCESS";
export const POST_BIO_SUCCESS="POST_BIO_SUCCESS";
export const PATCH_BIO_SUCCESS="PATCH_BIO_SUCCESS";

export const FETCH_BIOCARD_SUCCESS="FETCH_BIOCARD_SUCCESS";
export const POST_BIOCARD_SUCCESS="POST_BIOCARD_SUCCESS";
export const PATCH_BIOCARD_SUCCESS="PATCH_BIOCARD_SUCCESS";
export const DELETE_BIOCARD_SUCCESS="DELETE_BIOCARD_SUCCESS";

export const FETCH_BIOSKILL_SUCCESS="FETCH_BIOSKILL_SUCCESS";
export const POST_BIOSKILL_SUCCESS="POST_BIOSKILL_SUCCESS";
export const PATCH_BIOSKILL_SUCCESS="PATCH_BIOSKILL_SUCCESS";
export const DELETE_BIOSKILL_SUCCESS="DELETE_BIOSKILL_SUCCESS";

export const FETCH_PROJECT_SUCCESS="FETCH_PROJECT_SUCCESS";
export const POST_PROJECT_SUCCESS="POST_PROJECT_SUCCESS";
export const PATCH_PROJECT_SUCCESS="PATCH_PROJECT_SUCCESS";
export const DELETE_PROJECT_SUCCESS="DELETE_PROJECT_SUCCESS";

export const FETCH_CONTACT_SUCCESS="FETCH_CONTACT_SUCCESS";
export const POST_CONTACT_SUCCESS="POST_CONTACT_SUCCESS";
export const PATCH_CONTACT_SUCCESS="PATCH_CONTACT_SUCCESS";
export const DELETE_CONTACT_SUCCESS="DELETE_CONTACT_SUCCESS";

export const FETCH_SOCIAL_MEDIA_SUCCESS="FETCH_SOCIAL_MEDIA_SUCCESS";
export const POST_SOCIAL_MEDIA_SUCCESS="POST_SOCIAL_MEDIA_SUCCESS";
export const PATCH_SOCIAL_MEDIA_SUCCESS="PATCH_SOCIAL_MEDIA_SUCCESS";
export const DELETE_SOCIAL_MEDIA_SUCCESS="DELETE_SOCIAL_MEDIA_SUCCESS";

export const FETCH_TESTIMONIAL_SUCCESS="FETCH_TESTIMONIAL_SUCCESS";
export const POST_TESTIMONIAL_SUCCESS="POST_TESTIMONIAL_SUCCESS";
export const PATCH_TESTIMONIAL_SUCCESS="PATCH_TESTIMONIAL_SUCCESS";
export const DELETE_TESTIMONIAL_SUCCESS="DELETE_TESTIMONIAL_SUCCESS";

export const FETCH_EXPERIENCES_SUCCESS="FETCH_EXPERIENCES_SUCCESS";
export const POST_EXPERIENCES_SUCCESS="POST_EXPERIENCES_SUCCESS";
export const PATCH_EXPERIENCES_SUCCESS="PATCH_EXPERIENCES_SUCCESS";
export const DELETE_EXPERIENCES_SUCCESS="DELETE_EXPERIENCES_SUCCESS";

export const IS_ADMIN="IS_ADMIN";

